### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by betzrhodes**
- Initial library release
- Basic usage examples

### CODE REVIEW

**Comment by smittytone** [comment]
First thing: you'll want to check with Hugo, but AFAIK the existence of the imp006 has not been made public as an official product, so we probably don't want to mention it here in a public document. I may be wrong, so please do check.

**Comment by smittytone** [comment]
One other thing: do we want to indicate actual firmware version as well as library version in the enum? Not saying we should -- might make use responsible for keeping it up to date -- but some folks may want to know

**Review by smittytone — APPROVED** [review]
Add some comments to the PR thread, and updated the files as an initial edit.

**Comment by betzrhodes** [comment]
Thanks @smittytone 
- I've added the version strings for the firmware. 
- Hugo says it's ok to mention 006 here, although I've updated the wording he suggested.

**Comment by smittytone** [comment]
A couple of minor changes made, so that's good to go as far as I'm concerned. I'll update the Bluetooth BlinkUp sample code repo with the library goes live.

**Pull request merged**
